// frontend/src/pages/Registration.tsx
import { Component, createSignal, createEffect } from 'solid-js';
import { useNavigate } from '@solidjs/router';
import { UserService } from '../services';

const Registration: Component = () => {
  const [username, setUsername] = createSignal('');
  const [password, setPassword] = createSignal('');
  const [isLoading, setIsLoading] = createSignal(false);
  const [success, setSuccess] = createSignal(false);
  const navigate = useNavigate();
  
  const handleSubmit = async (e: Event) => {
    e.preventDefault();
    setIsLoading(true);
    
    try {
      // Register the user
      await UserService.register(username(), password());
      
      // Login the user to get the token
      const loginData = await UserService.login(username(), password());
      localStorage.setItem('token', loginData.access_token);
      setSuccess(true);
      navigate('/');
    } catch (error) {
      console.error('Registration failed:', error);
    } finally {
      setIsLoading(false);
    }
  };

  return (
    <div class="max-w-md mx-auto mt-10 p-6 bg-white dark:bg-gray-800 rounded-lg shadow-md">
      <h1 class="text-3xl font-bold text-gray-900 dark:text-white mb-6">Register New Account</h1>
      
      {success() && (
        <div class="bg-green-100 border border-green-400 text-green-700 dark:bg-green-900/30 dark:border-green-600 dark:text-green-400 px-4 py-3 rounded mb-4">
          <p class="text-lg font-medium">Registration successful!</p>
        </div>
      )}
      
      <form onSubmit={handleSubmit} class="space-y-4">
        <div>
          <label for="username" class="block text-sm font-medium text-gray-800 dark:text-gray-200 mb-1">Username</label>
          <input
            type="text"
            id="username"
            value={username()}
            onInput={(e) => setUsername(e.currentTarget.value)}
            required
            disabled={isLoading() || success()}
            class="w-full px-3 py-2 bg-white dark:bg-gray-700 border border-gray-300 dark:border-gray-600 rounded-md text-gray-900 dark:text-white shadow-sm focus:ring-indigo-500 focus:border-indigo-500"
          />
        </div>
        <div>
          <label for="password" class="block text-sm font-medium text-gray-800 dark:text-gray-200 mb-1">Password</label>
          <input
            type="password"
            id="password"
            value={password()}
            onInput={(e) => setPassword(e.currentTarget.value)}
            required
            disabled={isLoading() || success()}
            class="w-full px-3 py-2 bg-white dark:bg-gray-700 border border-gray-300 dark:border-gray-600 rounded-md text-gray-900 dark:text-white shadow-sm focus:ring-indigo-500 focus:border-indigo-500"
          />
        </div>
        <p class="text-sm text-gray-600 dark:text-gray-300 mt-2">
          Register a new account to participate in chess matches.
        </p>
        <button 
          type="submit" 
          disabled={isLoading() || success()}
          class="w-full mt-4 px-4 py-2 bg-indigo-600 text-white font-medium rounded-md hover:bg-indigo-700 focus:outline-none focus:ring-2 focus:ring-offset-2 focus:ring-indigo-500 transition-colors duration-200 disabled:opacity-50 disabled:cursor-not-allowed"
        >
          {isLoading() ? 'Registering...' : 'Register'}
        </button>
      </form>
    </div>
  );
};

export default Registration;

// frontend/src/app/pages/registration.component.ts
import { Component, inject } from '@angular/core';
import { CommonModule } from '@angular/common';
import {
  ReactiveFormsModule,
  FormGroup,
  FormControl,
  Validators,
} from '@angular/forms';
import { Router } from '@angular/router';
import { UserService } from '../services/user.service';

@Component({
  selector: 'app-registration',
  standalone: true,
  imports: [CommonModule, ReactiveFormsModule],
  template: `
    <div
      class="max-w-md mx-auto mt-10 p-6 bg-white dark:bg-gray-800 rounded-lg shadow-md"
    >
      <h1 class="text-3xl font-bold text-gray-900 dark:text-white mb-6">
        Register
      </h1>

      <div
        *ngIf="errorMessage"
        class="mb-4 p-3 bg-red-100 text-red-700 border border-red-200 rounded"
      >
        {{ errorMessage }}
      </div>

      <form
        [formGroup]="registrationForm"
        (ngSubmit)="onSubmit()"
        class="space-y-4"
      >
        <div>
          <label
            for="username"
            class="block text-sm font-medium text-gray-800 dark:text-gray-200 mb-1"
            >Username</label
          >
          <input
            type="text"
            id="username"
            formControlName="username"
            required
            [disabled]="isLoading"
            class="w-full px-3 py-2 bg-white dark:bg-gray-700 border border-gray-300 dark:border-gray-600 rounded-md text-gray-900 dark:text-white shadow-sm focus:ring-indigo-500 focus:border-indigo-500"
          />
          <div
            *ngIf="
              registrationForm.get('username')?.invalid &&
              registrationForm.get('username')?.touched
            "
            class="text-red-600 text-sm mt-1"
          >
            Username is required
          </div>
        </div>

        <div>
          <label
            for="password"
            class="block text-sm font-medium text-gray-800 dark:text-gray-200 mb-1"
            >Password</label
          >
          <input
            type="password"
            id="password"
            formControlName="password"
            required
            [disabled]="isLoading"
            class="w-full px-3 py-2 bg-white dark:bg-gray-700 border border-gray-300 dark:border-gray-600 rounded-md text-gray-900 dark:text-white shadow-sm focus:ring-indigo-500 focus:border-indigo-500"
          />
          <div
            *ngIf="
              registrationForm.get('password')?.invalid &&
              registrationForm.get('password')?.touched
            "
            class="text-red-600 text-sm mt-1"
          >
            Password is required
          </div>
        </div>

        <div>
          <label
            for="confirmPassword"
            class="block text-sm font-medium text-gray-800 dark:text-gray-200 mb-1"
            >Confirm Password</label
          >
          <input
            type="password"
            id="confirmPassword"
            formControlName="confirmPassword"
            required
            [disabled]="isLoading"
            class="w-full px-3 py-2 bg-white dark:bg-gray-700 border border-gray-300 dark:border-gray-600 rounded-md text-gray-900 dark:text-white shadow-sm focus:ring-indigo-500 focus:border-indigo-500"
          />
          <div
            *ngIf="
              registrationForm.get('confirmPassword')?.invalid &&
              registrationForm.get('confirmPassword')?.touched
            "
            class="text-red-600 text-sm mt-1"
          >
            Confirm password is required
          </div>
          <div
            *ngIf="
              registrationForm.get('confirmPassword')?.touched &&
              registrationForm.get('password')?.valid &&
              !passwordsMatch
            "
            class="text-red-600 text-sm mt-1"
          >
            Passwords do not match
          </div>
        </div>

        <button
          type="submit"
          [disabled]="registrationForm.invalid || !passwordsMatch || isLoading"
          class="w-full mt-4 px-4 py-2 bg-indigo-600 text-white font-medium rounded-md hover:bg-indigo-700 focus:outline-none focus:ring-2 focus:ring-offset-2 focus:ring-indigo-500 transition-colors duration-200 disabled:opacity-50 disabled:cursor-not-allowed"
        >
          {{ isLoading ? 'Registering...' : 'Register' }}
        </button>
      </form>
    </div>
  `,
})
export class RegistrationComponent {
  registrationForm = new FormGroup({
    username: new FormControl('', Validators.required),
    password: new FormControl('', Validators.required),
    confirmPassword: new FormControl('', Validators.required),
  });

  isLoading = false;
  errorMessage = '';

  private userService = inject(UserService);
  private router = inject(Router);

  get passwordsMatch(): boolean {
    const passwordValue = this.registrationForm.get('password')?.value;
    const confirmPasswordValue =
      this.registrationForm.get('confirmPassword')?.value;
    return passwordValue === confirmPasswordValue;
  }

  onSubmit(): void {
    if (this.registrationForm.invalid || !this.passwordsMatch) {
      return;
    }

    this.isLoading = true;
    this.errorMessage = '';

    const { username, password } = this.registrationForm.value;

    this.userService.register(username!, password!).subscribe({
      next: () => {
        this.isLoading = false;
        this.router.navigate(['/login']);
      },
      error: (error) => {
        this.isLoading = false;
        this.errorMessage = 'Registration failed. Please try again.';
        console.error('Registration error:', error);
      },
    });
  }
}
